name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:  # environment variables are variables that are available to all jobs and steps in the workflow. they are defined at the top level of the workflow file.
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}  

jobs: # jobs are the main building blocks of a workflow. each job runs in a fresh instance of the virtual environment and can run in parallel or sequentially.
    unit-testing:
        name: Unit Testing
        strategy:  # Used to test on different OS and nodejs versions
            matrix:  # matrix strategy is used to run the same job with different parameters. it's important because it allows us to test the code on different environments.
                nodejs_version: [18]  # can add 18 & 19
                operating_system: [ubuntu-latest, macos-latest]  # can add OS
                exclude:
                    - nodejs_version: 18
                      operating_system: macos-latest
        runs-on: ${{ matrix.operating_system }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.nodejs_version }}
        
        - name: Composite Action - Cache & Install NPM Packages   # Chaching to speed up the workflow
          uses: ./.github/custom-actions/npm-action
          with:
            path-of-folder: node_modules 
        - name: Unit Testing
          run: npm test

        - name: Archive Test Result
          if:  always()                      # excute even the previous step fails
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml
    code-coverage:
    
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - 18
          uses: actions/setup-node@v4 # this a
          with:
            node-version: 18

        - name: Composite Action - Cache & Install NPM Packages    # Chaching to speed up the workflow
          uses: ./.github/custom-actions/npm-action
          with:
            path-of-folder: node_modules
        - name: Check Code Coverage
          continue-on-error: true   # skip if there's an error
          run: npm run coverage

        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: Code-Coverage-Result
            path: coverage
            retention-days: 5
    docker:
        name: Containerization
        needs: [unit-testing, code-coverage]  # this job will run after the unit-testing and code-coverage jobs are completed successfully
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3.4.0
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}